/*******************************************************************/
/* calculateEfficiency.C                                           */
/* Helper function                                                 */
/* Based on comparisonplots.C by Isobel Ojalvo                     */
/* Author: Stephanie Kwan                                          */
/*******************************************************************/

#include "TCanvas.h"
#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TChain.h"
#include "TH1.h"
#include "TF1.h"
#include <math.h>
#include <TEfficiency.h>
#include <TMath.h>
#include <TFormula.h>
#include <iostream>
#include <string>

#include <iostream>
#include <cmath>
#include "TLegend.h"
#include "TPad.h"
#include "TH1.h"
#include "TH1F.h"
#include "TH2.h"
#include "TF1.h"
#include "THStack.h"
#include "TStyle.h"
#include "TAxis.h"
#include "TGaxis.h"
#include "TTree.h"
#include "TPaveText.h"
#include "tdrstyle.C"
#include "TStyle.h"
#include "TAxis.h"
#include "TGaxis.h"
#include "CMS_lumi.h"

#ifndef CALCULATE_EFFICIENCY_INCL
#define CALCULATE_EFFICIENCY_INCL

/*******************************************************************/

/* Applies template style to a TPad* pad1. */
void applyPadStyle(TPad* pad1)
{
  pad1->SetFillColor(0);
  pad1->Draw();
  pad1->cd();
  pad1->SetLeftMargin(0.2);  pad1->SetBottomMargin(0.13); pad1->SetRightMargin(0.1);
  //pad1->SetGrid(); 
  pad1->SetGrid(10,10); 
}

/*******************************************************************/

/* Apply legend style to a TLegend *leg. */

void applyLegStyle(TLegend *leg){
  leg->SetFillColor(0);
  leg->SetFillStyle(0);
  leg->SetBorderSize(0);
  leg->SetHeader("");
  leg->SetShadowColor(0);
}

/*******************************************************************/

/* Calculates and returns the efficiency of a BDT discriminant cut at
   the value workingPoint for Level 1 taus, using an efficiencyTree t,
   generated by the phase2L1TauAnalyzer. */
   
float calculateEfficiency(TString treePath, TString inputDirectory,
			  double genPtCut,
			  double recoPtCut,
			  double l1PtCut,
			  double absEtaCut,
			  double bdtCut)
{
  /* Load file */
  TFile *file = new TFile(inputDirectory);
  if (!file->IsOpen() || file==0 )
    {
      std::cout<<"ERROR FILE "<< inputDirectory <<" NOT FOUND; EXITING"<<std::endl;
      return 0;
    }
  
  TTree* tree = (TTree*)file->Get(treePath);
  if (tree == 0)
    {
      std::cout<<"ERROR Tau Tree is "<< tree<<" NOT FOUND; EXITING"<<std::endl;
      return 0;
    }

  int numerator = 0;
  int denominator = 0;
  
  /* Declare variables to read in */
  double recoPt, recoEta, recoPhi;
  double genPt, genEta, genPhi;
  double l1Pt, l1Eta, l1Phi;
  double l1DM;
  double l1PVDZ;
  double l1StripPt;

  /* Set branch addresses */
  tree->SetBranchAddress("recoPt",  &recoPt);
  tree->SetBranchAddress("recoEta", &recoEta);
  tree->SetBranchAddress("recoPhi", &recoPhi);
  tree->SetBranchAddress("genPt",  &genPt);
  tree->SetBranchAddress("genEta", &genEta);
  tree->SetBranchAddress("genPhi", &genPhi);
  tree->SetBranchAddress("l1Pt",  &l1Pt);
  tree->SetBranchAddress("l1Eta", &l1Eta);
  tree->SetBranchAddress("l1Phi", &l1Phi);

  tree->SetBranchAddress("l1DM", &l1DM);
  tree->SetBranchAddress("l1PVDZ", &l1PVDZ);
  tree->SetBranchAddress("l1StripPt", &l1StripPt);

  /* Loop through TTree. */
  for (int i = 0; i < tree->GetEntries(); i++)
    {
      tree->GetEntry(i);

      if (genPt > 20)
	numerator++;
      else
	denominator++;


    }
  if ((numerator > 0) && (denominator > 0))
    return (float) numerator/denominator;
  else
    return 0;

}

#endif
